#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

pnpm run format || (echo "⛔ Format failed" && exit 1)
pnpm run lint || (echo "⛔ Lint failed" && exit 1)
pnpm run build || (echo "⛔ Build failed" && exit 1)
