name: Deploy to Self-Hosted

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag ceboostxi-api
      - name: Run Docker image
        run: docker run -e PORT=${{secrets.PORT}} -e MONGO_URI=${{secrets.MONGO_URI}} -e ALLOWED_ORIGINS=${{secrets.ALLOWED_ORIGINS}} -e JWT_SECRET=${{secrets.JWT_SECRET}} -e NODE_ENV="production" -e AWS_BUCKET=${{secrets.AWS_BUCKET}} -e AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}} -e AWS_SECRET_ACCESS_KEY=${{secrets.AWS_ACCESS_KEY_ID}} -e AWS_REGION=${{secrets.AWS_REGION}} --name api -p 5050:5050 ceboostxi-api
