name: Deploy to Self-Hosted

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag ceboostxi-api
      - name: Run Docker image
        run: docker run --env PORT=${{ secrets.PORT }} --env MONGO_URI=${{ secrets.MONGO_URI }} --env ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS }} --env JWT_SECRET=${{ secrets.JWT_SECRET }} --env NODE_ENV="production" --env AWS_BUCKET=${{ secrets.AWS_BUCKET }} --env AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} --env AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} --env AWS_REGION=${{ secrets.AWS_REGION }} -p 5050:5050 ceboostxi-api
