name: Deploy to Self-Hosted

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build and Deploy
        env:
          PORT: ${{ secrets.PORT }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          ALLOWED_ORIGINS: ${{ secrets.ALLOWED_ORIGINS }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          NODE_ENV: 'production'
          AWS_BUCKET: ${{ secrets.AWS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          docker build --no-cache . \
            --file Dockerfile \
            --tag ceboostxi-api

          docker stop ceboostxi-api || true
          docker rm ceboostxi-api || true

          docker run --restart=always -d \
            -e PORT=$PORT \
            -e MONGO_URI=$MONGO_URI \
            -e ALLOWED_ORIGINS=$ALLOWED_ORIGINS \
            -e JWT_SECRET=$JWT_SECRET \
            -e NODE_ENV=$NODE_ENV \
            -e AWS_BUCKET=$AWS_BUCKET \
            -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
            -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
            -e AWS_REGION=$AWS_REGION \
            -p 5050:5050 \
            --name ceboostxi-api \
            ceboostxi-api
