name: Deploy to Self-Hosted

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Clear Cache
        run: |
          docker stop ceboostxi-api || true
          docker rm ceboostxi-api || true
          docker rmi ceboostxi-api:latest || true
      - name: Build Image
        run: |
          docker build --no-cache . \
            --file Dockerfile \
            --tag ceboostxi-api
      - name: Run Image
        run: |
          docker run --restart always -d \
            -e PORT=${{ secrets.PORT }} \
            -e MONGO_URI=${{ secrets.MONGO_URI }} \
            -e ALLOWED_ORIGINS=${{ secrets.ALLOWED_ORIGINS }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e AWS_BUCKET=${{ secrets.AWS_BUCKET }} \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -e AWS_REGION=${{ secrets.AWS_REGION }} \
            -e DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }} \
            -e DISCORD_WEBHOOK_USERNAME=${{ secrets.DISCORD_WEBHOOK_USERNAME }} \
            --network reverse-proxy_default \
            --name ceboostxi-api \
            ceboostxi-api:latest
